= Goaldi: A Goal-Directed Programming Language

Todd Proebsting and Gregg Townsend +
Department of Computer Science +
The University of Arizona

Goaldi is a new general-purpose programming language that combines
the goal-directed evaluation model of the
http://www.cs.arizona.edu/icon[Icon] language
with modern features such as concurrency, objects, closures,
and Unicode support.
While Goaldi will look familiar to Icon programmers,
it is not upwards compatible.

We're pleased with how Goaldi has turned out.
At this time the implementation is reasonably stable and robust,
and we're not actively developing it further.


== Download
The source code for Goaldi is maintained in a public repository on
https://github.com/proebsting/goaldi[GitHub].
Goaldi should run on any Unix-based platform that supports
http://golang.org/[Go].

We develop on Macintosh and Linux; pre-built binaries can be downloaded from the
https://github.com/proebsting/goaldi/releases[releases page].
Just unpack the appropriate *.tgz* file and run the *goaldi* executable.


== Documentation

* link:doc/intro.adoc[Introduction]
* link:doc/ref.adoc[Language Reference]
* link:doc/stdlib.adoc[Library Reference]
* link:doc/diffs.adoc[Goaldi for Icon Programmers]
* link:doc/build.adoc[Installation and Internals]


== Discussion List
A https://list.arizona.edu/sympa/info/goaldi-language[mailing list]
has been established for announcements and discussions.
Please https://list.arizona.edu/sympa/subscribe/goaldi-language[subscribe]
to stay informed of Goaldi developments.

== Contact Us Directly
Reach us by e-mail at goaldi@cs.arizona.edu.
